# Generated by Django 3.2.8 on 2021-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
