# Generated by Django 3.2.8 on 2021-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
