# Generated by Django 3.2.8 on 2021-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
