# Generated by Django 3.2.8 on 2022-01-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_alter_artwork_size'),
        ('profiles', '0006_userprofile_wishlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist_items',
            field=models.ManyToManyField(related_name='wishlist_artwork', to='artworks.Artwork'),
        ),
    ]
