# Generated by Django 3.2.8 on 2022-01-15 17:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_alter_artwork_stock'),
        ('profiles', '0009_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='wishlist_artwork', to='artworks.Artwork'),
        ),
    ]
