# Generated by Django 3.2.8 on 2021-12-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name_plural': 'Shop categories'},
        ),
    ]
