# Generated by Django 3.2.8 on 2021-12-23 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_shopcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Shop categories'},
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
