# Generated by Django 3.2.8 on 2021-12-23 13:10

from django.db import migrations
import portfolio.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_shopcategory_backend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='backend_name',
            field=portfolio.fields.CaseInsensitiveCharField(blank=True, max_length=150, null=True),
        ),
    ]
