# Generated by Django 3.2.8 on 2021-12-23 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portfolio.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfoliocategory_name'),
        ('artworks', '0005_alter_shopcategory_backend_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', portfolio.fields.CaseInsensitiveCharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('materials', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('draft', 'draft'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('display_shop', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfoliocategory')),
                ('related_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artwork')),
                ('shop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.shopcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
