# Generated by Django 3.2.8 on 2021-12-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfoliocategory_name'),
        ('artworks', '0006_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio'),
        ),
    ]
