# Generated by Django 3.2.8 on 2021-12-23 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_alter_artwork_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
