# Generated by Django 3.2.8 on 2021-12-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20211223_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
    ]
