# Generated by Django 3.2.8 on 2021-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20211223_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
    ]
