# Generated by Django 3.2.8 on 2021-12-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20211223_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='related_items',
            field=models.ManyToManyField(blank=True, related_name='_artworks_artwork_related_items_+', to='artworks.Artwork'),
        ),
    ]
