# Generated by Django 3.2.8 on 2022-01-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_alter_artwork_related_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='stock_alert',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
