# Generated by Django 3.2.8 on 2022-01-01 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_artwork_stock_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
    ]
