# Generated by Django 3.2.8 on 2022-01-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_alter_artwork_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(max_length=500, verbose_name='size(cm)'),
        ),
    ]
