# Generated by Django 3.2.8 on 2022-01-13 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_alter_artwork_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='stock',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
    ]
