# Generated by Django 3.2.8 on 2022-01-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20211219_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='email',
            new_name='email_newsletter',
        ),
    ]
