# Generated by Django 3.2.8 on 2021-12-29 13:21

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0006_userprofile_wishlist_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('gift_option', models.BooleanField(default=False)),
                ('gift_recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('gift_message', models.TextField(blank=True, max_length=1000, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bag', models.TextField(default='')),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('dispatched', 'disptached')], default='in progress', max_length=15)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
