# Generated by Django 3.2.8 on 2021-12-29 23:03

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='billing_county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='billing_postcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='billing_street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='billing_street_address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='billing_town_or_city',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street_address1',
            field=models.CharField(default='130 Glengall Road', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_town_or_city',
            field=models.CharField(default='London', max_length=40),
            preserve_default=False,
        ),
    ]
