# Generated by Django 3.2.8 on 2021-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_same_as_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
