# Generated by Django 3.2.8 on 2022-01-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_orderlineitem_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('dispatched', 'dispatched')], default='in progress', max_length=15),
        ),
    ]
