# Generated by Django 3.2.8 on 2022-01-09 15:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_postcode',
            field=models.CharField(blank=True, default='GB', max_length=20, null=True),
        ),
    ]
