# Generated by Django 3.2.8 on 2022-01-15 17:02

import checkout.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_delivery_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=django_countries.fields.CountryField(max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_country',
            field=django_countries.fields.CountryField(countries=checkout.models.Order.G8Countries, max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_recipient',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
