# Generated by Django 3.2.8 on 2022-01-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_alter_artwork_stock'),
        ('profiles', '0006_userprofile_wishlist_items'),
        ('checkout', '0006_alter_order_transaction_id'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Review',
        ),
    ]
