# Generated by Django 3.2.8 on 2022-01-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_alter_artwork_stock'),
        ('reviews', '0003_alter_review_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='artworks.artwork'),
        ),
    ]
