# Generated by Django 3.2.8 on 2022-01-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_wishlist_items'),
        ('reviews', '0004_alter_review_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.userprofile'),
        ),
    ]
