# Generated by Django 3.2.8 on 2022-01-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_alter_artwork_stock'),
        ('profiles', '0006_userprofile_wishlist_items'),
        ('reviews', '0005_alter_review_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork', to='artworks.artwork'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='profiles.userprofile'),
        ),
    ]
