# Generated by Django 3.2.8 on 2021-12-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortofolioCategory',
            new_name='PortfolioCategory',
        ),
    ]
