# Generated by Django 3.2.8 on 2021-12-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image_url',
        ),
    ]
