# Generated by Django 3.2.8 on 2021-12-22 21:28

from django.db import migrations
import portfolio.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=portfolio.fields.CaseInsensitiveCharField(max_length=150, unique=True),
        ),
    ]
